version: "3.9"

services:
  mclassbot:
    build: .
    container_name: mclassbot
    restart: unless-stopped
    env_file:
      - .env
    # Открываем порт FastAPI, если он нужен
    ports:
      - "8000:8000"


